# Generated by Django 5.0.7 on 2024-07-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_trainingpackage_userpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='workout_type',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='workout_types',
            field=models.ManyToManyField(to='workouts.workouttype'),
        ),
    ]
