# Generated by Django 5.0.7 on 2024-07-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_rename_user_userpackage_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='user_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.userpackage'),
        ),
    ]
